// <auto-generated />
namespace PROJECT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class like_error : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(like_error));
        
        string IMigrationMetadata.Id
        {
            get { return "201911260845496_like_error"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
